### ISSUE TITLE
Old value not defined

### ISSUE THREAD

**Issue by Dyceman** [mathvaleriano/vue-countup-directive#11]
![image](https://user-images.githubusercontent.com/3684442/53774695-8f929480-3ebd-11e9-8a93-dc0b41cf81d5.png)

nuxt.config.js
`plugins: [
    { src: '~/plugins/countup.js', ssr: false }
  ],`

countup.js
`import Vue from 'vue'
import options from 'vue-countup-directive'
Vue.directive('countUp', options)`

Version
`info Direct dependencies
└─ vue-countup-directive@1.2.3
info All dependencies
└─ vue-countup-directive@1.2.3
`

**Comment by mathvaleriano** [comment]
Hi. Thank you for report this issue, but I couldn't reproduce that. 
It seems like another **[issue]( #5 )** that has been fixed before.
Could you send me the component example that you are using?

**Comment by Dyceman** [comment]
`<span v-countUp="{ startValue: 0.35, endValue: 120.95, options: { duration: 1, decimals: 2 } }">`

**Comment by mathvaleriano** [comment]
I've tried to test with the code that you've sent me and everything was ok.
I couldn't reproduce this error. I used the latest version of the plugin with empty project. Could test reinstall the package with the latest version again? 
If you fix the error send an PR it'll be awesome too
