### ISSUE TITLE
i think it is a bug but i 'm not sure

### ISSUE THREAD

**Issue by chaosJS** [mathvaleriano/vue-countup-directive#5]
hello sir, when i change the data ,i'll get a error: `ReferenceError: oldvalue is not defined `
to avoid this error, i read the source code ,and i have to  rewrite the  `componentUpdated` function,
please check this link https://codesandbox.io/s/pkoq0wyrq7
![image](https://user-images.githubusercontent.com/17522683/52057285-a0d74100-259f-11e9-9186-20fdc4e769d6.png)

**Comment by mathvaleriano** [comment]
hey. thanks for reporting this issue. So... what version is installed? Because its a old issue that has already been solved

**Comment by mathvaleriano** [comment]
sorry about that.. i see this bug i'm going to fix it
thanks a lot
